# Generated by Django 6.0 on 2026-01-06 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image_cover',
            field=models.CharField(max_length=50, verbose_name='Kapak Resmi'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image_name',
            field=models.CharField(max_length=50, verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Başlık'),
        ),
    ]
