# Generated by Django 6.0 on 2026-01-16 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MinLengthValidator(5)]),
        ),
    ]
