# Generated by Django 6.0 on 2026-01-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_uploadmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default='', upload_to='images'),
        ),
    ]
