# Generated by Django 6.0 on 2026-01-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_product_imageurl_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
